// Central test runner for all rule .
import "./setupRuleTester";
import "./commands";
import "./settingsTab";
import "./platform.test";
import "./objectAssign.test";
import "./regexLookbehind.test";
import "./sampleNames.test";
import "./hardcodedConfigPath.test";
import "./vaultIterate.test";
import "./detachLeaves.test";
import "./preferFileManagerTrashFile.test";
import "./noTFileTFolderCast.test";
import "./noViewReferencesInPlugin.test";
import "./noStaticStylesAssignment.test";
import "./validateManifest.test";
import "./noPluginAsComponent.test";
import "./preferAbstractInputSuggest.test";
import "./noSampleCode.test";
